import React, { useState } from 'react';
import { AI_LAB_EXPERIMENTS } from '../../data/portfolioData';
import { RoomProps } from '../../experience/places';
import { Continue, Eyebrow, AnimatedPanel, ReadOn } from '../../experience/RoomParts';
export function AiLabUniverse({onTravelTo}: RoomProps) {
 const [index,setIndex] = useState(0);
 const [params,setParams] = useState<Record<string,string>>({});
 const experiment = AI_LAB_EXPERIMENTS[index];
 const probe = experiment.interactiveProbe;
 const key = probe?.parameters.map(p => params[p.id] || p.defaultVal).join('_') || '';
 const output = probe?.evaluations[key];
 return <div className="lab-room room-pad"><header className="lab-intro spacious-hero"><Eyebrow>02 / The observatory</Eyebrow><h1>Intelligence is<br/><em>a moving target.</em></h1><p>Memory. Personality. Perception.<br/>A few questions I’m teaching machines to ask.</p><ReadOn target="lab-instrument" label="Explore the studies"/></header><section id="lab-instrument" className="lab-instrument"><div className="experiment-selector"><Eyebrow>Select a study</Eyebrow>{AI_LAB_EXPERIMENTS.map((e,i) => <button key={e.id} aria-pressed={index===i} onClick={() => {setIndex(i);setParams({});}}><span>0{i+1}</span>{e.title.split(':')[0]}</button>)}</div><AnimatedPanel className="experiment-study" key={experiment.id}><div className="study-heading"><span className="eyebrow">Field notes / {experiment.status}</span><span className="study-mark" aria-hidden="true">⌖</span></div><h2>{experiment.title.split(':')[0]}</h2><p className="study-lead">{experiment.tagline}</p><div className="study-columns"><div><Eyebrow>The question</Eyebrow><p>{experiment.why}</p></div><div><Eyebrow>The approach</Eyebrow><p>{experiment.how}</p></div></div>{probe && <div className="probe"><Eyebrow>Interactive illustration / preset responses</Eyebrow><h3>{probe.title}</h3><p>{probe.description}</p><div className="probe-controls">{probe.parameters.map(p => <label key={p.id}>{p.label}<select value={params[p.id] || p.defaultVal} onChange={e => setParams(v => ({...v,[p.id]:e.target.value}))}>{p.options.map(o => <option key={o}>{o}</option>)}</select></label>)}</div><AnimatedPanel as="output" ariaLive="polite" key={key}>{output ? output.replace(/\[.*?\]\s*/, '') : 'This combination has no recorded illustration. Choose another setting to explore a documented response.'}</AnimatedPanel><small>A model of the idea, not a live AI inference or benchmark.</small></div>}<details className="study-notes"><summary>Open the research notebook <span>+</span></summary><Eyebrow>What was explored</Eyebrow><p>{experiment.whatWasExplored}</p><Eyebrow>What was learned</Eyebrow><p>{experiment.whatWasLearned}</p><p className="stack-line">{experiment.technologies.join(' / ')}</p></details></AnimatedPanel></section><Continue to="research" onTravelTo={onTravelTo}/></div>;
}

