import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, Search } from 'lucide-react';
import { PROJECTS_DATA } from '../../data/portfolioData';
import { RoomProps } from '../../experience/places';
import { Continue, Eyebrow, AnimatedPanel, ReadOn } from '../../experience/RoomParts';
export function BuilderUniverse({onTravelTo}: RoomProps) {
 const [selected,setSelected] = useState(PROJECTS_DATA[0].id);
 const [query,setQuery] = useState('');
 const [page,setPage] = useState<'idea'|'making'>('idea');
 const project = PROJECTS_DATA.find(p => p.id === selected)!;
 const filtered = PROJECTS_DATA.filter(p => `${p.title} ${p.category} ${p.stack.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const change = (id:string) => {setSelected(id); setPage('idea');};
 const index = PROJECTS_DATA.findIndex(p => p.id === selected);
 return <div className="workshop-room room-pad"><header className="room-intro spacious-hero"><Eyebrow>01 / The workshop</Eyebrow><h1>Thought becomes<br/><em>something real.</em></h1><p>A working collection of software, systems, and stubborn ideas.</p><ReadOn target="workbench" label="Step into the workshop"/></header>
 <section id="workbench" className="workbench" aria-label="Project workbench"><aside className="project-index"><div className="index-heading"><span className="eyebrow">The collection</span><span>{PROJECTS_DATA.length}</span></div><label className="project-search"><Search size={15}/><input aria-label="Find a project" placeholder="Find something…" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="project-list">{filtered.map(p => <button key={p.id} aria-pressed={selected===p.id} onClick={() => change(p.id)}><span>{String(PROJECTS_DATA.indexOf(p)+1).padStart(2,'0')}</span>{p.title}<ArrowUpRight size={14}/></button>)}{!filtered.length && <p className="empty-note">No projects match. Try another word.</p>}</div></aside>
 <AnimatedPanel as="article" className="project-folio" key={project.id}><div className="folio-top"><Eyebrow>Selected work / {String(index+1).padStart(2,'0')}</Eyebrow><span className="folio-stamp">{project.status}</span></div><span className="folio-watermark" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><h2>{project.title}</h2><p className="folio-tagline">{project.tagline}</p><div className="folio-tabs" aria-label="Project detail pages"><button aria-pressed={page==='idea'} onClick={() => setPage('idea')}>01 — The idea</button><button aria-pressed={page==='making'} onClick={() => setPage('making')}>02 — The making</button></div><AnimatedPanel className="folio-body" key={page}>{page==='idea' ? <><Eyebrow>The problem worth solving</Eyebrow><p>{project.problem}</p><div className="folio-facts"><div><Eyebrow>My role</Eyebrow><p>{project.role}</p></div><div><Eyebrow>Discipline</Eyebrow><p>{project.category}</p></div></div><ul className="quiet-list">{project.keyFeatures.map(f => <li key={f}>{f}</li>)}</ul></> : <><Eyebrow>Under the surface</Eyebrow><ol className="architecture-list">{project.architecture.map(a => <li key={a}>{a}</li>)}</ol><div className="stack-line">{project.stack.join(' / ')}</div><p>{project.executionEnvironment}</p></>}</AnimatedPanel><div className="folio-bottom"><a href={project.githubUrl} target="_blank" rel="noreferrer">Sobi on GitHub <ArrowUpRight size={14}/></a><div><button aria-label="Previous project" onClick={() => change(PROJECTS_DATA[(index-1+PROJECTS_DATA.length)%PROJECTS_DATA.length].id)}><ArrowLeft size={18}/></button><button aria-label="Next project" onClick={() => change(PROJECTS_DATA[(index+1)%PROJECTS_DATA.length].id)}><ArrowRight size={18}/></button></div></div></AnimatedPanel></section><Continue to="ai-lab" onTravelTo={onTravelTo}/></div>;
}

